---

- name: Log into proper cluster
  shell: oc login {{openshift_host}} --token={{openshift_token}} --insecure-skip-tls-verify=true

- name: Switch to proper project
  shell: oc project {{jdg_project}}

- name: Delete app (if exists)
  shell: oc delete all --selector=app=jdg-perf --timeout=1s
  ignore_errors: yes

- name: Import image
  shell: oc import-image --confirm slaskawi/summit-stress-test

- name: Create Perf tester
  shell: oc new-app --docker-image="slaskawi/summit-stress-test" --name=jdg-perf

- name: Expose a service
  shell: oc expose dc jdg-perf --port 8080

- name: Expose a route
  shell: oc expose svc jdg-perf
